### ISSUE TITLE
DisplayStyle::C can't print "jmp rax"

### ISSUE THREAD

**Issue by mstange** [iximeow/yaxpeax-x86#18]
```rust
fn main() {
    use yaxpeax_arch::Decoder;
    let decoder = yaxpeax_x86::amd64::InstDecoder::default();
    let inst = decoder.decode_slice(&[0xFF, 0xE0]).unwrap();
    println!("{}", inst.display_with(yaxpeax_x86::amd64::DisplayStyle::C));
}
```

hits the `unreachable!` in `write_jmp_operand`:

https://github.com/iximeow/yaxpeax-x86/blob/1dc77c26e1de52f43b0841f60c42f9581ac31f77/src/long_mode/display.rs#L3519-L3537

**Comment by iximeow** [comment]
thank you for the report! `DisplayStyle::C` slipped by with the fuzzing that landed recently and, lo, it had a bug.

i've fixed this reachable `unreachable` and added the same "display must not panic" fuzzing for `DisplayStyle::C` as we have for `DisplayStyle::Intel`, in [`e80b562`](https://github.com/iximeow/yaxpeax-x86/commit/e80b5622ec956a92f24ce6487fb0d76e9c541515). with that patch, fuzzing seems to have no further issues, and i've published a `yaxpeax-x86 1.1.4` that includes the fix.

**Comment by mstange** [comment]
Thanks!

**Comment by mstange** [comment]
It appears that 1.1.4 hasn't been published yet.

**Comment by iximeow** [comment]
agh, i tagged the commit but must have forgot to `cargo publish`. [actually published now](https://crates.io/crates/yaxpeax-x86/1.1.4).

**Comment by mstange** [comment]
Thank you!
