### ISSUE TITLE
`CALL ptr16:16/ptr16:32` is not decodable in protected or real mode

### ISSUE THREAD

**Issue by i509VCB** [iximeow/yaxpeax-x86#22]
Per the Intel manual, there is a valid Opcode in Compat/Legacy mode at `0x9A`.

This does not return a `Opcode::CALL` in real mode or protected mode decoders:
- https://github.com/iximeow/yaxpeax-x86/blob/no-gods-no-/src/real_mode/mod.rs#L5405
- https://github.com/iximeow/yaxpeax-x86/blob/no-gods-no-/src/protected_mode/mod.rs#L5405

Long mode appears to be correct.

![Screenshot_20220411_221715](https://user-images.githubusercontent.com/30619168/162872702-f3e2a112-3dd0-4b73-ba91-d507eeba671a.png)

**Comment by iximeow** [comment]
well, that's a little awkward. i assume the immediate address encoding must have been removed in the change because they considered an 8-byte address to be unwieldy or something (fair?)

didn't know the 9a encoding existed at all.. i suppose yaxpeax-x86 would benefit from differential fuzzing too.

**Comment by iximeow** [comment]
ok! finally found the time to add this encoding. [`073d3b36`](https://github.com/iximeow/yaxpeax-x86/commit/073d3b367ee4164fc5c89c4a7869770f0261a00c) if you track git directly, or hopefully i'll get a new `1.1.5` release up shortly if you're using a cargo dep.
