### ISSUE TITLE
Checking if opcode is a conditional jump

### ISSUE THREAD

**Issue by meithecatte** [iximeow/yaxpeax-x86#29]
Currently, `Opcode::condition` provides some facilities for handling Jcc, SETcc and CMOVcc with common code for the condition codes themselves. However, you still need to list all the 16 conditional jumps in a match, or do ugly string processing hacks, to actually check whether an Opcode is a Jcc, or whether it is SETcc or CMOVcc.

**Comment by iximeow** [comment]
this feels like a glaring oversight! i'm surprised i'd never noticed this either. `is_jcc`, `is_setcc`, and `is_cmovc` helpers on the various `Opcode` certainly seem reasonable to me.

**Comment by iximeow** [comment]
(those helpers are now on all three forms of `Opcode`, and will get published as part of an eventual 1.1.6 release)
