### ISSUE TITLE
Misrender of backwards jumps

### ISSUE THREAD

**Issue by chc4** [iximeow/yaxpeax-x86#7]
`ja $+0x1e` good
`jna $+-0x1e` bad

**Comment by iximeow** [comment]
what are the bytes behind `good`/`bad`? i assume good -> `771e` and bad -> `76e1`? and "good" on the second case would be `jna $-0x1e`?

**Comment by iximeow** [comment]
much happier with this now: https://github.com/iximeow/yaxpeax-x86/commit/dff9a7e4a14984705db8fb18550af5a4fa9ce3d5
