### ISSUE TITLE
Decode `endbr{32,64}`

### ISSUE THREAD

**Issue by ranweiler** [iximeow/yaxpeax-x86#8]
The special CET nops for indirect branch termination don't yet seem to be known to yax. This is easy to work around, when it matters, but it would be nice to e.g. have the right `Display` impls.

**Expected:**
```
$ yaxdis f30f1efa
0x00000000: f30f1efa      : endbr64

$ yaxdis f30f1efb
0x00000000: f30f1efb      : endbr32
```

**Actual:**
```
$ yaxdis f30f1efa
0x00000000: f30f1efa      : nop edx

$ yaxdis f30f1efb
0x00000000: f30f1efb      : nop ebx
```

**Comment by iximeow** [comment]
fixed in [`ed5c76a`](https://github.com/iximeow/yaxpeax-x86/commit/ed5c76a0f8e92656539f305b9b7ea5e032517f36) and published as `1.1.1`, thanks for filing the issue!
